package com.lifeos.expensecapture.data.db.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Learned merchant -> category mappings. Two distinct origins now coexist here (Automation
 * Rules PRD, Phase 3 Doc 34, requires this distinction be visible, not just functional):
 * - createdFromUserCorrection = true: the AI's OWN inferred automation, silently created when
 *   a user corrects a transaction's category (Automation Philosophy's learning behavior -
 *   explicitly out of scope for Doc 34).
 * - createdFromUserCorrection = false (and isManuallyAuthored = true): a rule the user
 *   deliberately typed in via the Automation Rules screen - the actual "user-authored rule"
 *   Doc 34 is about, a materially different trust relationship per that PRD's own framing.
 *
 * isPaused lets a user temporarily disable a rule without losing it (Doc 34 Feature Scope:
 * "pause a rule temporarily without deleting it, in case my situation changes").
 *
 * Bug fix (found via a real user report, 2026-07): merchantPattern has a unique index so
 * MerchantRuleDao.upsert()'s OnConflictStrategy.REPLACE actually has something to conflict on.
 * Before this, correcting the same merchant a second time (even fixing a mis-tap) always
 * inserted a brand new row instead of replacing the old one - id is autogenerated and always 0
 * on a fresh correction, so it never collided with anything, meaning "upsert" was silently just
 * "insert." Multiple contradictory rules for the same merchant then made categorize()'s
 * first-match lookup pick whichever one happened to come first, ignoring the user's latest
 * correction. See MIGRATION_12_13 for how existing duplicates are resolved.
 */
@Entity(tableName = "merchant_rules", indices = [Index(value = ["merchantPattern"], unique = true)])
data class MerchantRuleEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val merchantPattern: String,
    val categoryId: Long,
    val createdFromUserCorrection: Boolean = false,
    val isManuallyAuthored: Boolean = false,
    val isPaused: Boolean = false,
    /** Predefined categorization rules (2026-08, real user request: "Predefined Categorization
     * rules Coming soon") - a third, distinct origin from the two above: seeded once from
     * data/seed/DefaultMerchantRules.kt (see App.seedDefaultMerchantRulesOnce), not created by
     * this specific user at all. CategorizationEngine.categorize() gives real user rules
     * (createdFromUserCorrection or isManuallyAuthored) priority over these when both match the
     * same transaction - a seeded default must never silently shadow a real user correction. */
    val isSeededDefault: Boolean = false
)
